/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all jobs
         * @description Retrieve a list of all registered cron jobs with optional label filtering
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter jobs by label (format: key=value) */
                    label?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved job list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        /**
         * Create a new job
         * @description Register a new cron job with automatic API key generation
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateJobRequest"];
                };
            };
            responses: {
                /** @description Job created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                409: components["responses"]["ConflictError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get job by ID
         * @description Retrieve a specific job by its ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully retrieved job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        /**
         * Update job by ID
         * @description Update an existing job configuration
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateJobRequest"];
                };
            };
            responses: {
                /** @description Job updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        post?: never;
        /**
         * Delete job by ID
         * @description Remove a job from the system
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Job ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["UnauthorizedError"];
                404: components["responses"]["NotFoundError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit job execution result
         * @description Submit the result of a cron job execution using the job's unique API key
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            responses: {
                /** @description Job result submitted successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                400: components["responses"]["BadRequestError"];
                401: components["responses"]["UnauthorizedError"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Retrieve Prometheus-formatted metrics for all registered jobs
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics in text format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check the health status of the API server
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard runtime configuration
         * @description Returns non-secret configuration for the embedded portal. This path is relative to the configured dashboard base path.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard runtime configuration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardRuntimeConfig"];
                    };
                };
                401: components["responses"]["DashboardUnauthorizedError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search dashboard jobs
         * @description Returns a bounded, filtered page of jobs. This path is relative to the configured dashboard base path.
         */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    name?: string;
                    host?: string;
                    status?: "active" | "maintenance" | "paused";
                    page?: number;
                    page_size?: number;
                    before?: string;
                    after?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated dashboard job results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobSearchResult"];
                    };
                };
                400: components["responses"]["DashboardBadRequestError"];
                401: components["responses"]["DashboardUnauthorizedError"];
            };
        };
        put?: never;
        /** Create a dashboard job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateJobRequest"];
                };
            };
            responses: {
                /** @description Job created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["DashboardBadRequestError"];
                401: components["responses"]["DashboardUnauthorizedError"];
                409: components["responses"]["DashboardConflictError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get a dashboard job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                401: components["responses"]["DashboardUnauthorizedError"];
                404: components["responses"]["DashboardNotFoundError"];
            };
        };
        /** Update a dashboard job */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateJobRequest"];
                };
            };
            responses: {
                /** @description Updated job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                400: components["responses"]["DashboardBadRequestError"];
                401: components["responses"]["DashboardUnauthorizedError"];
                404: components["responses"]["DashboardNotFoundError"];
                409: components["responses"]["DashboardConflictError"];
            };
        };
        post?: never;
        /** Delete a dashboard job */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["DashboardUnauthorizedError"];
                404: components["responses"]["DashboardNotFoundError"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle dashboard job maintenance status */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Toggled job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                401: components["responses"]["DashboardUnauthorizedError"];
                404: components["responses"]["DashboardNotFoundError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream dashboard invalidation events
         * @description Opens an SSE stream relative to the configured dashboard base path. Event data uses the DashboardEvent schema.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server-Sent Events stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                401: components["responses"]["DashboardUnauthorizedError"];
                /** @description SSE disabled or client limit reached */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Job: {
            /**
             * @description Auto-incrementing job ID
             * @example 1
             */
            id: number;
            /**
             * @description Unique job name
             * @example daily-backup
             */
            job_name: string;
            /**
             * @description Host where the job runs
             * @example db-server-01
             */
            host: string;
            /**
             * @description Per-job API key for result submissions
             * @example cm_abc123456789abcdef123456789abcdef123456789abcd
             */
            api_key?: string;
            /**
             * @description Seconds after which job is considered failed if no result submitted
             * @example 3600
             */
            automatic_failure_threshold: number;
            /**
             * @description User-defined labels for the job
             * @example {
             *       "env": "prod",
             *       "team": "platform",
             *       "type": "backup"
             *     }
             */
            labels: {
                [key: string]: string;
            };
            /**
             * @description Job lifecycle status
             * @example active
             * @enum {string}
             */
            status: "active" | "maintenance" | "paused";
            /**
             * Format: date-time
             * @description Timestamp of last result submission
             * @example 2025-10-30T19:56:00Z
             */
            last_reported_at: string;
            /**
             * Format: date-time
             * @description Job creation timestamp
             * @example 2025-10-30T10:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Job last update timestamp
             * @example 2025-10-30T19:56:00Z
             */
            updated_at: string;
        };
        CreateJobRequest: {
            /**
             * @description Unique job name
             * @example daily-backup
             */
            job_name: string;
            /**
             * @description Host where the job runs
             * @example db-server-01
             */
            host: string;
            /**
             * @description Custom API key (optional, auto-generated if not provided)
             * @example cm_custom123456789abcdef123456789abcdef123456789abc
             */
            api_key?: string;
            /**
             * @description Seconds after which job is considered failed (default: 3600)
             * @example 7200
             */
            automatic_failure_threshold?: number;
            /**
             * @description User-defined labels for the job
             * @example {
             *       "env": "prod",
             *       "team": "platform",
             *       "type": "backup"
             *     }
             */
            labels?: {
                [key: string]: string;
            };
            /**
             * @description Job lifecycle status (default: active)
             * @example active
             * @enum {string}
             */
            status?: "active" | "maintenance" | "paused";
        };
        UpdateJobRequest: {
            /**
             * @description Updated job name
             * @example daily-backup-v2
             */
            job_name?: string;
            /**
             * @description Updated host name
             * @example db-server-02
             */
            host?: string;
            /**
             * @description Updated API key
             * @example cm_new123456789abcdef123456789abcdef123456789abcd
             */
            api_key?: string;
            /**
             * @description Updated failure threshold in seconds
             * @example 7200
             */
            automatic_failure_threshold?: number;
            /**
             * @description Updated labels (replaces existing labels completely)
             * @example {
             *       "env": "staging",
             *       "team": "devops"
             *     }
             */
            labels?: {
                [key: string]: string;
            };
            /**
             * @description Updated job status
             * @example maintenance
             * @enum {string}
             */
            status?: "active" | "maintenance" | "paused";
        };
        JobResult: {
            /**
             * @description Name of the job (must match API key)
             * @example daily-backup
             */
            job_name: string;
            /**
             * @description Host name (must match API key)
             * @example db-server-01
             */
            host: string;
            /**
             * @description Execution result status
             * @example success
             * @enum {string}
             */
            status: "success" | "failure";
            /**
             * @description Additional labels for this execution
             * @example {
             *       "env": "prod",
             *       "backup_type": "full"
             *     }
             */
            labels?: {
                [key: string]: string;
            };
            /**
             * @description Execution duration in seconds
             * @example 120
             */
            duration?: number;
            /**
             * @description Optional execution output or error message
             * @example Backup completed successfully. 1.2GB transferred.
             */
            output?: string;
            /**
             * Format: date-time
             * @description Execution timestamp (defaults to current time if not provided)
             * @example 2025-10-30T19:56:00Z
             */
            timestamp?: string;
        };
        SuccessResponse: {
            /** @example true */
            success?: boolean;
            /** @example Job result submitted successfully */
            message?: string;
            /**
             * Format: date-time
             * @example 2025-10-30T19:56:00Z
             */
            timestamp?: string;
        };
        ErrorResponse: {
            /**
             * @description Error message
             * @example Job name and host are required
             */
            error: string;
            /**
             * Format: date-time
             * @description Error timestamp
             * @example 2025-10-30T19:56:00Z
             */
            timestamp: string;
        };
        HealthResponse: {
            /** @example ok */
            status?: string;
            /**
             * Format: date-time
             * @example 2025-10-30T19:56:00Z
             */
            timestamp?: string;
            /** @example 0.3.0 */
            version?: string;
        };
        DashboardRuntimeConfig: {
            /** @example /dashboard */
            base_path: string;
            /** @example Cron Monitor */
            title: string;
            /** @example 25 */
            page_size: number;
            /** @example true */
            sse_enabled: boolean;
            /** @example true */
            polling_fallback: boolean;
            /** @example 5 */
            polling_interval: number;
        };
        JobSearchResult: {
            jobs: components["schemas"]["Job"][];
            total_count: number;
            page: number;
            page_size: number;
            total_pages: number;
            has_next: boolean;
            has_previous: boolean;
            search_query?: string;
        };
        DashboardEvent: {
            id: string;
            /** @enum {string} */
            type: "connected" | "heartbeat" | "reset" | "job-status-change" | "job-created" | "job-updated" | "job-deleted";
            job_id?: number;
            /** Format: date-time */
            timestamp: string;
        };
        DashboardError: {
            /** @example validation */
            code: string;
            /** @example job validation failed */
            message: string;
            fields?: {
                [key: string]: string;
            };
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: {
        /** @description Invalid dashboard request */
        DashboardBadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DashboardError"];
            };
        };
        /** @description Missing or invalid dashboard Basic credentials */
        DashboardUnauthorizedError: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DashboardError"];
            };
        };
        /** @description Dashboard job not found */
        DashboardNotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DashboardError"];
            };
        };
        /** @description Dashboard job conflicts with an existing job */
        DashboardConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DashboardError"];
            };
        };
        /** @description Bad request - invalid input data */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Job name and host are required",
                 *       "timestamp": "2025-10-30T19:56:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized - missing or invalid API key */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "missing or invalid API key",
                 *       "timestamp": "2025-10-30T19:56:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "job not found",
                 *       "timestamp": "2025-10-30T19:56:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict - resource already exists */
        ConflictError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "job already exists",
                 *       "timestamp": "2025-10-30T19:56:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "failed to create job",
                 *       "timestamp": "2025-10-30T19:56:00Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
